FROM debian:buster

RUN set -ex \
    && sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
               autoconf \
               automake \
               build-essential \
               cdbs \
               cmake \
               curl \
               devscripts \
               equivs \
               fakeroot \
               meson \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/*
